
from game_model.AI_model.action_output import ActionOutput
from game_model.AI_model.gamestate_input import GamestateInputVector
from game_model.AI_model.maps import map_from_AI_output
from game_model.game import Game
from game_model.game_runner import step_game
from game_model.resource_types import ResourceType
from tests.test_helpers import assert_banks, test_config
from game_model.turn import Turn,Action_Type

def test_game_state_input_correct_length_flat_map():
    empty_input = GamestateInputVector()
    flat_map = empty_input.flat_map()
    all_keys = flat_map.keys()
    str = ", ".join(all_keys)
    assert len(flat_map.keys()) == 107
    expected_keys = [
        "player_0_temp_resources",
        "player_0_perm_resources",
        "player_0_points",
        "player_0_reserved_card_0_costs",
        "player_0_reserved_card_0_returns",
        "player_0_reserved_card_0_points",
        "player_0_reserved_card_1_costs",
        "player_0_reserved_card_1_returns",
        "player_0_reserved_card_1_points",
        "player_0_reserved_card_2_costs",
        "player_0_reserved_card_2_returns",
        "player_0_reserved_card_2_points",
        "player_1_temp_resources",
        "player_1_perm_resources",
        "player_1_points",
        "player_1_reserved_card_0_costs",
        "player_1_reserved_card_0_returns",
        "player_1_reserved_card_0_points",
        "player_1_reserved_card_1_costs",
        "player_1_reserved_card_1_returns",
        "player_1_reserved_card_1_points",
        "player_1_reserved_card_2_costs",
        "player_1_reserved_card_2_returns",
        "player_1_reserved_card_2_points",
        "player_2_temp_resources",
        "player_2_perm_resources",
        "player_2_points",
        "player_2_reserved_card_0_costs",
        "player_2_reserved_card_0_returns",
        "player_2_reserved_card_0_points",
        "player_2_reserved_card_1_costs",
        "player_2_reserved_card_1_returns",
        "player_2_reserved_card_1_points",
        "player_2_reserved_card_2_costs",
        "player_2_reserved_card_2_returns",
        "player_2_reserved_card_2_points",
        "player_3_temp_resources",
        "player_3_perm_resources",
        "player_3_points",
        "player_3_reserved_card_0_costs",
        "player_3_reserved_card_0_returns",
        "player_3_reserved_card_0_points",
        "player_3_reserved_card_1_costs",
        "player_3_reserved_card_1_returns",
        "player_3_reserved_card_1_points",
        "player_3_reserved_card_2_costs",
        "player_3_reserved_card_2_returns",
        "player_3_reserved_card_2_points",
        "noble_0_costs",
        "noble_0_points",
        "noble_1_costs",
        "noble_1_points",
        "noble_2_costs",
        "noble_2_points",
        "noble_3_costs",
        "noble_3_points",
        "noble_4_costs",
        "noble_4_points",
        "tier_0_card_0_costs",
        "tier_0_card_0_returns",
        "tier_0_card_0_points",
        "tier_0_card_1_costs",
        "tier_0_card_1_returns",
        "tier_0_card_1_points",
        "tier_0_card_2_costs",
        "tier_0_card_2_returns",
        "tier_0_card_2_points",
        "tier_0_card_3_costs",
        "tier_0_card_3_returns",
        "tier_0_card_3_points",
        "tier_0_hidden_card_costs",
        "tier_0_hidden_card_returns",
        "tier_0_hidden_card_points",
        "tier_0_points",
        "tier_1_card_0_costs",
        "tier_1_card_0_returns",
        "tier_1_card_0_points",
        "tier_1_card_1_costs",
        "tier_1_card_1_returns",
        "tier_1_card_1_points",
        "tier_1_card_2_costs",
        "tier_1_card_2_returns",
        "tier_1_card_2_points",
        "tier_1_card_3_costs",
        "tier_1_card_3_returns",
        "tier_1_card_3_points",
        "tier_1_hidden_card_costs",
        "tier_1_hidden_card_returns",
        "tier_1_hidden_card_points",
        "tier_1_points",
        "tier_2_card_0_costs",
        "tier_2_card_0_returns",
        "tier_2_card_0_points",
        "tier_2_card_1_costs",
        "tier_2_card_1_returns",
        "tier_2_card_1_points",
        "tier_2_card_2_costs",
        "tier_2_card_2_returns",
        "tier_2_card_2_points",
        "tier_2_card_3_costs",
        "tier_2_card_3_returns",
        "tier_2_card_3_points",
        "tier_2_hidden_card_costs",
        "tier_2_hidden_card_returns",
        "tier_2_hidden_card_points",
        "tier_2_points",
        "resources"
    ]

    for expected in expected_keys:
        assert expected in flat_map