[package]
name = "rust_splendor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delegate = "0.10.0"
seq-macro = "0.3.5"
rand = "0.8.5"
rand_chacha = "0.3.1"
